### ISSUE TITLE
taipy is installed but display.py won't run

### ISSUE THREAD

**Issue by wiflexmobile** [AlexandreSajus/JARVIS#9]
Hi Alex, 

Thanks for this wonderful project, it really looks interesting and is useful. 

Anyway, I already run pip install -r requirements.txt and it went straight without errors. 

When I try to run python display.py, I am getting following error:

C:\Users\wiflex\Documents\Projects\JARVIS>python display.py
Traceback (most recent call last):
  File "C:\Users\wiflex\Documents\Projects\JARVIS\display.py", line 5, in <module>
    from taipy.gui import Gui, State, invoke_callback, get_state_id
ModuleNotFoundError: No module named 'taipy'

However if I run pip list command, I can see that the following taipy packages are installed:

taipy                         3.0.0
taipy-config                  3.0.0
taipy-core                    3.0.0
taipy-gui                     3.0.0
taipy-rest                    3.0.0
taipy-templates               3.0.0

As well in VS Code I am getting this:

![image](https://github.com/AlexandreSajus/JARVIS/assets/144247489/2696a0cb-36a8-46f2-8173-3b930666bb44)

Thanks in advance for any help.

**Comment by AlexandreSajus** [comment]
Can you try running `python -m pip list` instead of `pip list`. `python -m pip` and `pip` might be calling different versions of Python.

If this shows that taipy is not installed, reinstall it using `python -m pip install -r requirements.txt` and try running again

Elsewise, create a clean virtual environment and install requirements there:
- `python -m venv venv`
- `.\venv\Scripts\activate`
- `pip install -r requirements.txt`
- `python display.py`

Let me know if this fixes the issue
